//! Rendering. Pure — it takes the manifest values and the overlay TEXT, so the
//! shape of the output is testable without touching a filesystem.

use gates_config::Config;
use std::path::PathBuf;

/// The banner every rendered file carries. Present so a human editing the file
/// directly learns, in the file itself, that their edit will be overwritten.
pub const BANNER: &str =
    "<!-- Generated by render-agent-docs. Edit the manifest or the overlay, not this file. -->";

#[derive(Debug, Clone, PartialEq, Eq)]
pub struct Target {
    pub name: String,
    pub path: String,
    pub title: String,
}

#[derive(Debug, Clone, PartialEq, Eq)]
pub struct Manifest {
    /// Rule fragment names, in the order they should load.
    pub rules: Vec<String>,
    /// Directory containing Markdown rule fragments to embed.
    pub rules_dir: String,
    /// Path to the repo-specific body, appended after the rules block.
    pub overlay: Option<String>,
    pub targets: Vec<Target>,
}

impl Manifest {
    pub fn from_config(cfg: &Config) -> Manifest {
        let targets = cfg
            .tables_under("targets")
            .into_iter()
            .filter_map(|name| {
                let path = cfg.string(&format!("targets.{name}.path"))?.to_string();
                let title = cfg
                    .string(&format!("targets.{name}.title"))
                    .unwrap_or(&path)
                    .to_string();
                Some(Target { name, path, title })
            })
            .collect();
        Manifest {
            rules: cfg.list("rules").unwrap_or_default(),
            rules_dir: cfg
                .string("rules_dir")
                .unwrap_or("rules")
                .trim_end_matches('/')
                .to_string(),
            overlay: cfg.string("overlay").map(str::to_string),
            targets,
        }
    }
}

#[derive(Debug, Clone, PartialEq, Eq)]
pub struct Rule {
    pub name: String,
    pub text: String,
}

pub fn load_rules(manifest: &Manifest) -> Result<Vec<Rule>, String> {
    let base = expand_home(&manifest.rules_dir);
    manifest
        .rules
        .iter()
        .map(|name| {
            let path = base.join(format!("{name}.md"));
            let text =
                std::fs::read_to_string(&path).map_err(|e| format!("{}: {e}", path.display()))?;
            Ok(Rule {
                name: name.clone(),
                text,
            })
        })
        .collect()
}

fn expand_home(path: &str) -> PathBuf {
    let Some(rest) = path.strip_prefix("~/") else {
        return PathBuf::from(path);
    };
    std::env::var_os("HOME")
        .map(PathBuf::from)
        .unwrap_or_default()
        .join(rest)
}

/// The full text of one target file.
///
/// Whole-file generation is deliberate. A "managed region" between markers
/// leaves the rest hand-written, and the hand-written rest is exactly where the
/// two files drift apart. Anything a repo needs to say for itself goes in the
/// overlay, which both targets share.
pub fn render(target: &Target, overlay: Option<&str>, rules: &[Rule]) -> String {
    let mut out = String::new();
    out.push_str(&format!("# {}\n\n", target.title));
    out.push_str(BANNER);
    out.push_str("\n\n");

    if !rules.is_empty() {
        out.push_str("## Rules\n\n");
        out.push_str("Generated from portable fragments; edit source rules and re-render.\n\n");
        for rule in rules {
            out.push_str(&format!("### {}\n\n", rule.name));
            out.push_str(rule_body(&rule.text));
            out.push_str("\n\n");
        }
    }

    if let Some(body) = overlay {
        let body = body.trim_start_matches('\u{feff}').trim();
        if !body.is_empty() {
            out.push_str(body);
            out.push('\n');
        }
    }
    out
}

fn rule_body(text: &str) -> &str {
    let text = text.trim_start_matches('\u{feff}').trim();
    if !text.starts_with("# ") {
        return text;
    }
    text.split_once('\n')
        .map(|(_, body)| body.trim_start())
        .unwrap_or("")
}

#[cfg(test)]
#[path = "render_tests.rs"]
mod render_tests;
